<a href="https://colab.research.google.com/github/MikeIV2007/Data-science-HW/blob/main/DS_HW_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [2]:
# 1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
print (a)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [4]:
# 2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

zero = np.zeros([3,3])
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# 3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

random_int = np.random.randint(1, 11, size=(5, 5))
print(random_int)

[[ 9 10  8  8  2]
 [ 7  7  8  7  7]
 [ 9  5  7  6  6]
 [ 7  6  6  9  3]
 [ 5  4  1  5  2]]


In [7]:
# 4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

random_float = np.random.rand(4, 4)
print(random_float)

[[0.64223836 0.22676712 0.6935949  0.69516895]
 [0.70131414 0.74335223 0.77980673 0.41405372]
 [0.13862514 0.72637352 0.93487962 0.28956312]
 [0.7831278  0.3167628  0.98517909 0.55896467]]


In [19]:
# 5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення

b=np.random.randint(1,11, size=5)
print(b)
c=np.random.randint(1,11, size=5)
print(c)

sum = b+c
print (sum)

sub = b-c
print (sub)

mult = b*c
print(mult)

[8 8 5 7 1]
[6 8 6 5 2]
[14 16 11 12  3]
[ 2  0 -1  2 -1]
[48 64 30 35  2]


In [14]:
# 6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
first=np.random.randint(1,100, size=7)
print(first)
second=np.random.randint(1,100, size=7)
print(second)

mult=np.dot(first,second)
print(mult)

[67  4 26 42 85 77 41]
[76 89 22 37 70 61 71]
21132


In [3]:
# 7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

first=np.random.randint(1,11, size=(2,2))
print(first)
second=np.random.randint(1,11, size=(2,3))
print(second)

mult=np.dot(first,second)
print(mult)

[[4 6]
 [5 9]]
[[8 2 1]
 [1 5 8]]
[[38 38 52]
 [49 55 77]]


In [5]:
# 8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

matrix=np.random.randint(1,11, size=(3,3))
print(matrix)

inverse_matrix = matrix.T
print(inverse_matrix)

[[2 3 5]
 [4 5 3]
 [2 1 7]]
[[2 4 2]
 [3 5 1]
 [5 3 7]]


In [9]:
# 9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

matrix=np.random.rand(4,4)
print(matrix)

inverse_matrix = matrix.T
print (inverse_matrix)

[[0.0575529  0.05752287 0.48017307 0.16819217]
 [0.86574338 0.14010371 0.26880155 0.00625222]
 [0.10745374 0.34410396 0.0708489  0.9348767 ]
 [0.66990095 0.41891613 0.9875219  0.61422005]]
[[0.0575529  0.86574338 0.10745374 0.66990095]
 [0.05752287 0.14010371 0.34410396 0.41891613]
 [0.48017307 0.26880155 0.0708489  0.9875219 ]
 [0.16819217 0.00625222 0.9348767  0.61422005]]


In [10]:
# 10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
matrix=np.random.randint(1,11, size=(3,4))
print(matrix)
vector=np.random.randint(1,11, size=4)
print(vector)

mult=np.dot(matrix, vector)
print (mult)

[[ 6  4  7  3]
 [ 8  3  4  4]
 [ 7 10  2  3]]
[8 6 7 3]
[130 122 139]


In [11]:
# 11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
matrix=np.random.rand(2,3)
print(matrix)
vector=np.random.rand(3)
print(vector)

mult=np.dot(matrix, vector)
print (mult)

[[0.39501026 0.16813133 0.08665249]
 [0.94980183 0.9237147  0.41909286]]
[0.93373672 0.88653923 0.67041912]
[0.57598409 1.98674204]


In [14]:
# 12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
matrix1=np.random.randint(1,11, size=(2,2))
print(matrix1)
matrix2=np.random.randint(1,11, size=(2,2))
print(matrix2)

mult=matrix1*matrix2
print (mult)

[[3 4]
 [5 4]]
[[ 5  6]
 [ 5 10]]
[[15 24]
 [25 40]]


In [15]:
# 13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
matrix1=np.random.randint(1,11, size=(2,2))
print(matrix1)
matrix2=np.random.randint(1,11, size=(2,2))
print(matrix2)

mult=np.dot(matrix1,matrix2)
print (mult)

[[10  3]
 [ 9  8]]
[[8 1]
 [7 8]]
[[101  34]
 [128  73]]


In [16]:
# 14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
matrix=np.random.randint(1,101, size=(5,5))
print(matrix)

matrix_sum=np.sum(matrix)
print(matrix_sum)

[[ 9 64 71 80  8]
 [ 5 35 97 20 69]
 [25 42 18 79 90]
 [16 27  5 56 80]
 [95 11 62 78 93]]
1235


In [17]:
# 15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrix1=np.random.randint(1,11, size=(4,4))
print(matrix1)
matrix2=np.random.randint(1,11, size=(4,4))
print(matrix2)

sub = matrix1-matrix2
print(sub)

[[ 2  6  9 10]
 [ 4 10  3  6]
 [ 8  8 10  2]
 [10 10  7  1]]
[[ 7  2  2 10]
 [ 2  5  2 10]
 [ 3  4  4  5]
 [ 1  7  5 10]]
[[-5  4  7  0]
 [ 2  5  1 -4]
 [ 5  4  6 -3]
 [ 9  3  2 -9]]


In [18]:
# 16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix=np.random.rand(3,3)
print(matrix)

row_sums = np.sum(matrix, axis=1, keepdims=True)
print(row_sums)


[[0.64803343 0.85864182 0.4560368 ]
 [0.455537   0.60473058 0.51347568]
 [0.51198358 0.00366219 0.17381243]]
[[1.96271205]
 [1.57374326]
 [0.6894582 ]]


In [23]:
# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matrix=np.random.randint(1,11, size=(3,4))
print (matrix)

squared = np.square(matrix)
print (squared)

[[ 5  6  5  3]
 [ 1 10  5  6]
 [ 5  5 10 10]]
[[ 25  36  25   9]
 [  1 100  25  36]
 [ 25  25 100 100]]


In [24]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
vector = np.random.randint(1,51, size=4)
print(vector)

srt = np.sqrt(vector)
print (srt)

[ 1  1 38  8]
[1.         1.         6.164414   2.82842712]
